## IGNORE FOR NOW
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-producthandler-api
  namespace: rso-deploy
  annotations:
    kubernetes.io/ingress.global-static-ip-name: product-handler.com
    kubernetes.io/ingress.class: nginx    

spec:
  rules:
  - host: product-handler.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: producthandler-service
              port:
                number: 8000

status:
  loadBalancer:
    ingress:
      - ip: 20.85.162.42