apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rso-deploy-pvc
  namespace: rso-deploy
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: rso-deploy-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rso-deploy-pv
  namespace: rso-deploy
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres-pv-local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: rso-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-container
  template:
    metadata:
      labels:
        name: postgres-container
        tier: backend
    spec:
      containers:
        - name: postgres-container
          image: postgres:10.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: database
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: rso-deploy-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rso-deploy-postgres
  namespace: rso-deploy
spec:
  type: NodePort
  selector:
    name: postgres-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432